version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://trade_user:password@db:5432/trade_db
    depends_on:
      db:
        condition: service_healthy  # Wait for db to be healthy
    volumes:
      - .:/app

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=trade_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=trade_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U trade_user"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: