name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t trade-api:latest .

      - name: Deploy to EC2 via SSH
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          echo "$EC2_SSH_KEY" > bl_house.pem
          chmod 600 bl_house.pem

          ssh -o StrictHostKeyChecking=no -i ssh_key.pem $EC2_USER@$EC2_HOST << 'EOF'
          rm -rf /home/$EC2_USER/blockhouse_assignments
          mkdir -p /home/$EC2_USER/blockhouse_assignments
          EOF
          scp -o StrictHostKeyChecking=no -i ssh_key.pem -r . $EC2_USER@$EC2_HOST:/home/$EC2_USER/blockhouse_assignments/
          ssh -o StrictHostKeyChecking=no -i ssh_key.pem $EC2_USER@$EC2_HOST << 'EOF'
          cd /home/$EC2_USER/blockhouse_assignments
          docker-compose down
          docker-compose up --build -d
          EOF
          

          rm bl_house.pem