name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'  # Only run on PRs
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with mock DB
        run: |
          pytest tests/
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t trade-api:latest .

      - name: Create stable tarball
        run: |
          mkdir -p temp-deploy
          rsync -a --exclude='temp-deploy' --exclude='.git' ./ temp-deploy/
          cd temp-deploy
          tar -czf ../app.tar.gz .
          cd ..
          rm -rf temp-deploy
      

      - name: Deploy to EC2 via SSH
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          echo "EC2_HOST: $EC2_HOST"
          if [ -z "$EC2_HOST" ] || [ -z "$EC2_USER" ] || [ -z "$EC2_SSH_KEY" ]; then
            echo "One or more secrets are empty!"
            exit 1
          fi
          echo "$EC2_SSH_KEY" > ssh_key.pem
          chmod 600 ssh_key.pem
          ssh -o StrictHostKeyChecking=no -i ssh_key.pem $EC2_USER@$EC2_HOST << 'EOF'
            rm /home/ubuntu/app.tar.gz
          EOF
          scp -o StrictHostKeyChecking=no -i ssh_key.pem app.tar.gz $EC2_USER@$EC2_HOST:/home/ubuntu/
          ssh -o StrictHostKeyChecking=no -i ssh_key.pem $EC2_USER@$EC2_HOST << 'EOF'
            mkdir -p blockhouse_assignments
            cd blockhouse_assignments/
            tar -xzf /home/$EC2_USER/app.tar.gz --overwrite
            rm /home/$EC2_USER/app.tar.gz
            docker-compose down
            docker-compose up --build -d
          EOF
          rm ssh_key.pem

 